# Generated by Django 5.2 on 2026-01-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categore',
            new_name='category',
        ),
    ]
